// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ParkingSystem.Models;

namespace ParkingSystem.Migrations
{
    [DbContext(typeof(ParkingSystemContext))]
    [Migration("20190130132912_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ParkingSystem.Models.Admin", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Login")
                        .IsRequired();

                    b.Property<string>("Password")
                        .IsRequired();

                    b.HasKey("ID");

                    b.ToTable("Admin");
                });

            modelBuilder.Entity("ParkingSystem.Models.Customer", b =>
                {
                    b.Property<int>("CustomerID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email");

                    b.Property<string>("FirstName")
                        .IsRequired();

                    b.Property<string>("LastName")
                        .IsRequired();

                    b.Property<string>("PhoneNo")
                        .IsRequired();

                    b.Property<string>("Position");

                    b.Property<int?>("PositionDiscountPositionID");

                    b.HasKey("CustomerID");

                    b.HasIndex("PositionDiscountPositionID");

                    b.ToTable("Customer");
                });

            modelBuilder.Entity("ParkingSystem.Models.ParkingSlot", b =>
                {
                    b.Property<int>("ParkingID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CustomerID");

                    b.Property<string>("Plate")
                        .IsRequired();

                    b.Property<DateTime>("TimeIn");

                    b.Property<DateTime?>("TimeOut");

                    b.HasKey("ParkingID");

                    b.HasIndex("CustomerID");

                    b.ToTable("ParkingSlot");
                });

            modelBuilder.Entity("ParkingSystem.Models.Payment", b =>
                {
                    b.Property<int>("ReceiptNo")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ParkingID");

                    b.Property<int>("Period");

                    b.Property<int?>("PricingID");

                    b.Property<DateTime>("TimeOfPayment");

                    b.Property<decimal>("Total");

                    b.HasKey("ReceiptNo");

                    b.HasIndex("ParkingID");

                    b.HasIndex("PricingID");

                    b.ToTable("Payment");
                });

            modelBuilder.Entity("ParkingSystem.Models.PositionDiscount", b =>
                {
                    b.Property<int>("PositionID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Position")
                        .IsRequired();

                    b.Property<float>("Price");

                    b.HasKey("PositionID");

                    b.ToTable("PositionDiscount");
                });

            modelBuilder.Entity("ParkingSystem.Models.Pricing", b =>
                {
                    b.Property<int>("PricingID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Period");

                    b.Property<float>("Price");

                    b.HasKey("PricingID");

                    b.ToTable("Pricing");
                });

            modelBuilder.Entity("ParkingSystem.Models.Customer", b =>
                {
                    b.HasOne("ParkingSystem.Models.PositionDiscount", "PositionDiscount")
                        .WithMany("CustomerID")
                        .HasForeignKey("PositionDiscountPositionID");
                });

            modelBuilder.Entity("ParkingSystem.Models.ParkingSlot", b =>
                {
                    b.HasOne("ParkingSystem.Models.Customer", "Customer")
                        .WithMany("ParkingID")
                        .HasForeignKey("CustomerID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ParkingSystem.Models.Payment", b =>
                {
                    b.HasOne("ParkingSystem.Models.ParkingSlot", "ParkingSlot")
                        .WithMany("PaymentID")
                        .HasForeignKey("ParkingID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ParkingSystem.Models.Pricing", "Pricing")
                        .WithMany("PaymentID")
                        .HasForeignKey("PricingID");
                });
#pragma warning restore 612, 618
        }
    }
}
