// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ParkingSystem.Models;

namespace ParkingSystem.Migrations
{
    [DbContext(typeof(ParkingSystemContext))]
    partial class ParkingSystemContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ParkingSystem.Models.Admin", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Login")
                        .IsRequired();

                    b.Property<string>("Password")
                        .IsRequired();

                    b.HasKey("ID");

                    b.ToTable("Admin");
                });

            modelBuilder.Entity("ParkingSystem.Models.Customer", b =>
                {
                    b.Property<int>("CustomerID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email");

                    b.Property<string>("FirstName")
                        .IsRequired();

                    b.Property<string>("LastName")
                        .IsRequired();

                    b.Property<int?>("ParkingSlotParkingID");

                    b.Property<int?>("PaymentReceiptNo");

                    b.Property<string>("PhoneNo")
                        .IsRequired();

                    b.HasKey("CustomerID");

                    b.HasIndex("ParkingSlotParkingID");

                    b.HasIndex("PaymentReceiptNo");

                    b.ToTable("Customer");
                });

            modelBuilder.Entity("ParkingSystem.Models.ParkingSlot", b =>
                {
                    b.Property<int>("ParkingID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("PaymentReceiptNo");

                    b.Property<string>("Plate")
                        .IsRequired();

                    b.Property<DateTime>("TimeIn");

                    b.Property<DateTime?>("TimeOut");

                    b.HasKey("ParkingID");

                    b.HasIndex("PaymentReceiptNo");

                    b.ToTable("ParkingSlot");
                });

            modelBuilder.Entity("ParkingSystem.Models.Payment", b =>
                {
                    b.Property<int>("ReceiptNo")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("TimeOfPayment");

                    b.Property<decimal>("Total");

                    b.HasKey("ReceiptNo");

                    b.ToTable("Payment");
                });

            modelBuilder.Entity("ParkingSystem.Models.PositionDiscount", b =>
                {
                    b.Property<string>("Position")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("CustomerID");

                    b.Property<decimal>("Price");

                    b.HasKey("Position");

                    b.HasIndex("CustomerID");

                    b.ToTable("PositionDiscount");
                });

            modelBuilder.Entity("ParkingSystem.Models.Pricing", b =>
                {
                    b.Property<int>("Period")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("PaymentReceiptNo");

                    b.Property<decimal>("Price");

                    b.HasKey("Period");

                    b.HasIndex("PaymentReceiptNo");

                    b.ToTable("Pricing");
                });

            modelBuilder.Entity("ParkingSystem.Models.Customer", b =>
                {
                    b.HasOne("ParkingSystem.Models.ParkingSlot")
                        .WithMany("CustomerID")
                        .HasForeignKey("ParkingSlotParkingID");

                    b.HasOne("ParkingSystem.Models.Payment")
                        .WithMany("CustomerID")
                        .HasForeignKey("PaymentReceiptNo");
                });

            modelBuilder.Entity("ParkingSystem.Models.ParkingSlot", b =>
                {
                    b.HasOne("ParkingSystem.Models.Payment")
                        .WithMany("ParkingID")
                        .HasForeignKey("PaymentReceiptNo");
                });

            modelBuilder.Entity("ParkingSystem.Models.PositionDiscount", b =>
                {
                    b.HasOne("ParkingSystem.Models.Customer")
                        .WithMany("Position")
                        .HasForeignKey("CustomerID");
                });

            modelBuilder.Entity("ParkingSystem.Models.Pricing", b =>
                {
                    b.HasOne("ParkingSystem.Models.Payment")
                        .WithMany("Period")
                        .HasForeignKey("PaymentReceiptNo");
                });
#pragma warning restore 612, 618
        }
    }
}
